#!/usr/bin/env python3
"""Generate review-backed manuscript figures from workflow artifacts.

This script keeps figure generation inside the repository workflow instead of
relying on one-off notebook or shell snippets. It does not run experiments; it
visualizes the current protocol-estimated CSV values and deterministic protocol
diagrams.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Optional


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def uncertainty(value: str) -> float:
    cleaned = value.replace("+-", "").replace("±", "").strip()
    try:
        return float(cleaned)
    except ValueError:
        return 0.0


def pick(
    rows: list[dict[str, str]],
    metric: str,
    methods: list[str],
    dataset_contains: Optional[str] = None,
) -> list[tuple[str, float, float]]:
    selected: list[tuple[str, float, float]] = []
    for method in methods:
        matches = [
            row
            for row in rows
            if row.get("metric") == metric and row.get("method") == method
        ]
        if dataset_contains:
            matches = [
                row
                for row in matches
                if dataset_contains in row.get("dataset_bucket", "")
            ]
        if not matches:
            continue
        row = matches[0]
        selected.append(
            (
                method,
                float(row.get("predicted_value", "0")),
                uncertainty(row.get("uncertainty", "0")),
            )
        )
    return selected


def draw_architecture_figure(plt, output: Path) -> None:
    """Draw the deterministic candidate-instantiation architecture diagram."""
    import matplotlib.patches as patches

    fig, ax = plt.subplots(figsize=(9.4, 4.8), constrained_layout=True)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")

    def box(x: float, y: float, w: float, h: float, label: str, color: str) -> None:
        rect = patches.FancyBboxPatch(
            (x, y),
            w,
            h,
            boxstyle="round,pad=0.04,rounding_size=0.07",
            facecolor=color,
            edgecolor="#242424",
            linewidth=1.0,
        )
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center", fontsize=9)

    def arrow(x1: float, y1: float, x2: float, y2: float) -> None:
        ax.annotate(
            "",
            xy=(x2, y2),
            xytext=(x1, y1),
            arrowprops={"arrowstyle": "->", "lw": 1.2, "color": "#242424"},
        )

    box(0.3, 3.0, 1.45, 0.8, "Road-crack\nimages", "#d9e8ff")
    box(2.15, 3.0, 1.55, 0.8, "YOLO\nbackbone", "#dff2e2")
    box(4.05, 3.0, 1.75, 0.8, "Shape-aware\nneck", "#f5ead0")
    box(6.2, 3.0, 1.65, 0.8, "Thin-crack\nheads", "#f5dede")
    box(8.25, 3.0, 1.45, 0.8, "Boxes,\nmasks,\nscores", "#e4dff4")

    for x1, x2 in [(1.75, 2.15), (3.7, 4.05), (5.8, 6.2), (7.85, 8.25)]:
        arrow(x1, 3.4, x2, 3.4)

    box(2.0, 1.25, 2.1, 0.85, "Hard-negative\nsampling queue", "#f0f0f0")
    box(4.55, 1.25, 2.1, 0.85, "Boundary +\nelongation losses", "#f0f0f0")
    box(7.1, 1.25, 2.1, 0.85, "Matched-budget\nprotocol hooks", "#f0f0f0")
    arrow(3.05, 2.1, 4.85, 3.0)
    arrow(5.6, 2.1, 5.15, 3.0)
    arrow(8.15, 2.1, 7.1, 3.0)

    ax.text(
        0.35,
        5.35,
        "Candidate detector instantiation inside a protocol-first evaluation contract",
        fontsize=12,
        weight="bold",
    )
    ax.text(
        0.35,
        0.35,
        "Diagram is generated by scripts/generate_predicted_figures.py from the fixed workflow spec; it is not measured model evidence.",
        fontsize=8,
        color="#555555",
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_module_detail_figure(plt, output: Path) -> None:
    """Draw a module-level view of the proposed crack-aware fusion block."""
    import matplotlib.patches as patches

    fig, ax = plt.subplots(figsize=(9.6, 5.4), constrained_layout=True)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 7)
    ax.axis("off")

    def box(x: float, y: float, w: float, h: float, label: str, color: str) -> None:
        rect = patches.FancyBboxPatch(
            (x, y),
            w,
            h,
            boxstyle="round,pad=0.04,rounding_size=0.07",
            facecolor=color,
            edgecolor="#242424",
            linewidth=1.0,
        )
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, label, ha="center", va="center", fontsize=8.5)

    def arrow(x1: float, y1: float, x2: float, y2: float) -> None:
        ax.annotate(
            "",
            xy=(x2, y2),
            xytext=(x1, y1),
            arrowprops={"arrowstyle": "->", "lw": 1.1, "color": "#242424"},
        )

    ax.text(0.25, 6.45, "Crack-Aware Fusion Module", fontsize=13, weight="bold")
    ax.text(
        0.25,
        6.05,
        "Module design to be tested in the future empirical branch; no weights are trained in this run.",
        fontsize=8,
        color="#555555",
    )

    for y, label in [
        (4.9, "P3\nfine texture"),
        (3.55, "P4\nmid scale"),
        (2.2, "P5\ncontext"),
    ]:
        box(0.35, y, 1.45, 0.75, label, "#d9e8ff")
        arrow(1.8, y + 0.38, 2.45, 3.9)

    box(2.45, 3.5, 1.65, 0.85, "Shared\n1x1 align", "#eef1f5")
    box(4.55, 4.85, 1.65, 0.85, "Horizontal\nstrip pool", "#f5ead0")
    box(4.55, 3.55, 1.65, 0.85, "Vertical\nstrip pool", "#f5ead0")
    box(4.55, 2.25, 1.65, 0.85, "Diagonal\nedge probe", "#f5ead0")
    arrow(4.1, 3.92, 4.55, 5.25)
    arrow(4.1, 3.92, 4.55, 3.98)
    arrow(4.1, 3.92, 4.55, 2.68)

    box(6.65, 3.55, 1.45, 0.85, "Elongation\ngate", "#dff2e2")
    arrow(6.2, 5.25, 6.65, 3.98)
    arrow(6.2, 3.98, 6.65, 3.98)
    arrow(6.2, 2.68, 6.65, 3.98)

    box(8.55, 4.45, 1.15, 0.75, "Detect\nhead", "#f5dede")
    box(8.55, 2.75, 1.15, 0.75, "Thin\nhead", "#e4dff4")
    arrow(8.1, 3.98, 8.55, 4.82)
    arrow(8.1, 3.98, 8.55, 3.12)

    formula = (
        r"$G_e=\sigma(W_g[P_h,P_v,P_d]),\quad "
        r"F_c=P_3+\sum_s G_{e,s}\odot W_sP_s$"
    )
    ax.text(2.25, 0.85, formula, fontsize=11)
    ax.text(
        2.25,
        0.45,
        "The equation defines the intended fusion hypothesis; it is not evidence of a trained module.",
        fontsize=8,
        color="#555555",
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_mechanism_equation_figure(plt, output: Path) -> None:
    """Draw a compact map linking model mechanisms to planned formulas."""
    import matplotlib.patches as patches

    fig, ax = plt.subplots(figsize=(9.6, 5.4), constrained_layout=True)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 7)
    ax.axis("off")

    ax.text(0.25, 6.45, "Mechanism and Formula Map", fontsize=13, weight="bold")
    ax.text(
        0.25,
        6.05,
        "Each formula is a planned analysis object for the future measured branch.",
        fontsize=8,
        color="#555555",
    )

    rows = [
        (
            4.9,
            "Thin-structure supervision",
            r"$L_{thin}=L_{dice}+\lambda_b L_{boundary}+\lambda_c L_{cont}$",
            "continuity and boundary fidelity",
            "#d9e8ff",
        ),
        (
            3.65,
            "Hard-negative queue",
            r"$w_i=1+\gamma\,1[x_i\in Q_{hard}]$",
            "shadow, sealed joint, and lane-mark confusion",
            "#f5ead0",
        ),
        (
            2.4,
            "Forecast calibration",
            r"$\hat m=m_{lit}+\Delta_{module}-\rho_{risk}$",
            "conservative planning center, not a measurement",
            "#dff2e2",
        ),
        (
            1.15,
            "Stop/go criterion",
            r"$Go=1[\Delta_{mAP}>0.015\wedge FP/img<\tau]$",
            "future run acceptance rule",
            "#e4dff4",
        ),
    ]

    for y, title, formula, note, color in rows:
        rect = patches.FancyBboxPatch(
            (0.45, y),
            2.0,
            0.78,
            boxstyle="round,pad=0.04,rounding_size=0.07",
            facecolor=color,
            edgecolor="#242424",
            linewidth=1.0,
        )
        ax.add_patch(rect)
        ax.text(1.45, y + 0.39, title, ha="center", va="center", fontsize=8.5)
        ax.annotate(
            "",
            xy=(3.05, y + 0.39),
            xytext=(2.45, y + 0.39),
            arrowprops={"arrowstyle": "->", "lw": 1.0, "color": "#242424"},
        )
        ax.text(3.15, y + 0.49, formula, fontsize=10.5, va="center")
        ax.text(3.15, y + 0.15, note, fontsize=8, color="#555555", va="center")

    ax.text(
        0.45,
        0.35,
        "This diagram increases mathematical traceability without claiming executed losses, gradients, or benchmark measurements.",
        fontsize=8,
        color="#555555",
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def draw_benchmark_matrix_figure(plt, output: Path) -> None:
    """Draw the deterministic benchmark coverage matrix."""
    methods = [
        "YOLOv8s",
        "YOLOv8-PD",
        "BL-YOLOv8",
        "RT-DETR",
        "DeepCrack",
        "CrackFormer",
        "CrackYOLO-R",
    ]
    columns = [
        "Same\nbudget",
        "Crack\nspecific",
        "Hard\nnegatives",
        "Speed\ncheck",
        "Stats\nplan",
    ]
    values = [
        [3, 1, 2, 3, 2],
        [3, 3, 2, 2, 2],
        [3, 3, 2, 2, 2],
        [2, 1, 2, 1, 2],
        [1, 3, 2, 1, 2],
        [1, 3, 2, 1, 2],
        [3, 3, 3, 3, 3],
    ]

    fig, ax = plt.subplots(figsize=(8.8, 5.8), constrained_layout=True)
    image = ax.imshow(values, cmap="YlGnBu", vmin=0, vmax=3)
    ax.set_xticks(range(len(columns)), labels=columns)
    ax.set_yticks(range(len(methods)), labels=methods)
    ax.tick_params(axis="both", labelsize=9)
    ax.set_title("Planned Benchmark Coverage Matrix", fontsize=13, weight="bold")

    for row_idx, row in enumerate(values):
        for col_idx, value in enumerate(row):
            ax.text(
                col_idx,
                row_idx,
                str(value),
                ha="center",
                va="center",
                color="#111111" if value < 2 else "white",
                fontsize=8,
                weight="bold",
            )

    cbar = fig.colorbar(image, ax=ax, shrink=0.86)
    cbar.set_label("0-3 protocol coverage priority, not performance", fontsize=9)
    fig.text(
        0.5,
        0.02,
        "Cells encode planned coverage pressure for the evaluation contract; they are not measured or forecast scores.",
        ha="center",
        fontsize=8.5,
        color="#555555",
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--app-dir", default=".", help="Application root directory")
    parser.add_argument(
        "--output",
        default=None,
        help="Output PNG path; default: <app-dir>/figures/predicted_yolo_crack_results.png",
    )
    args = parser.parse_args()

    root = Path(args.app_dir)
    csv_path = root / "predicted_results" / "predicted_results.csv"
    output = (
        Path(args.output)
        if args.output
        else root / "figures" / "predicted_yolo_crack_results.png"
    )

    rows = read_rows(csv_path)
    if not rows:
        raise SystemExit(f"No predicted rows found: {csv_path}")

    try:
        import matplotlib.pyplot as plt
    except Exception as exc:  # pragma: no cover - environment failure path
        raise SystemExit(f"matplotlib is required to generate figures: {exc}")

    panels = [
        (
            "Crack500 boxes",
            "mAP50-95",
            pick(
                rows,
                "mAP50-95",
                ["YOLOv8s baseline", "Faster R-CNN baseline", "CrackYOLO-R full"],
                "Crack500",
            ),
            "higher",
        ),
        (
            "RDD2022 crack subset",
            "mAP50-95",
            pick(
                rows,
                "mAP50-95",
                [
                    "YOLOv8s baseline",
                    "YOLOv8-PD baseline",
                    "Improved YOLOv8s road-defect baseline",
                    "BL-YOLOv8 baseline",
                    "Damage Shape Adaptation detector",
                    "RT-DETR-R18/R50 family",
                    "CrackYOLO-R full",
                ],
                "RDD2022",
            ),
            "higher",
        ),
        (
            "Thin-structure masks",
            "F1@thin-crack",
            pick(
                rows,
                "F1@thin-crack",
                [
                    "YOLOv8s-seg baseline",
                    "DeepCrack segmentation baseline",
                    "CrackFormer baseline",
                    "Crack Transformer baseline",
                    "ViT crack detector baseline",
                    "CrackYOLO-R-seg full",
                ],
                "DeepCrack",
            ),
            "higher",
        ),
        (
            "Hard-negative audit",
            "FP/image",
            pick(
                rows,
                "false_positive_per_image",
                [
                    "YOLOv8s baseline",
                    "Damage Shape Adaptation detector",
                    "CrackYOLO-R full",
                ],
                "Shadow",
            ),
            "lower",
        ),
        (
            "Edge imagery",
            "FPS@640",
            pick(rows, "FPS@640", ["YOLOv8n baseline", "CrackYOLO-R-nano"], "Inspection"),
            "higher",
        ),
    ]

    if not any(panel[2] for panel in panels):
        raise SystemExit("No known method/metric rows found for predicted figure panels")

    plt.rcParams.update(
        {
            "font.size": 8,
            "font.family": "DejaVu Sans",
            "axes.spines.top": False,
            "axes.spines.right": False,
        }
    )
    fig, axes = plt.subplots(2, 3, figsize=(10.2, 5.8), constrained_layout=True)
    flat_axes = axes.ravel()

    colors = {
        "CrackYOLO-R full": "#2a7f62",
        "CrackYOLO-R-seg full": "#2a7f62",
        "CrackYOLO-R-nano": "#2a7f62",
        "YOLOv8s baseline": "#4a6fa5",
        "YOLOv8n baseline": "#4a6fa5",
        "YOLOv8s-seg baseline": "#4a6fa5",
        "Improved YOLOv8s road-defect baseline": "#5c5c5c",
        "YOLOv8-PD baseline": "#5c5c5c",
        "BL-YOLOv8 baseline": "#5c5c5c",
        "Damage Shape Adaptation detector": "#8a6d3b",
        "CrackFormer baseline": "#7b4fa3",
        "Crack Transformer baseline": "#7b4fa3",
        "ViT crack detector baseline": "#7b4fa3",
        "DeepCrack segmentation baseline": "#7b4fa3",
        "Faster R-CNN baseline": "#9a4f4f",
        "RT-DETR-R18/R50 family": "#9a4f4f",
    }
    label_map = {
        "YOLOv8s baseline": "YOLOv8s",
        "YOLOv8n baseline": "YOLOv8n",
        "Faster R-CNN baseline": "Faster R-CNN",
        "YOLOv8-PD baseline": "YOLOv8-PD",
        "Improved YOLOv8s road-defect baseline": "Imp. YOLOv8s",
        "BL-YOLOv8 baseline": "BL-YOLOv8",
        "Damage Shape Adaptation detector": "DSA detector",
        "RT-DETR-R18/R50 family": "RT-DETR",
        "YOLOv8s-seg baseline": "YOLOv8s-seg",
        "DeepCrack segmentation baseline": "DeepCrack",
        "CrackFormer baseline": "CrackFormer",
        "Crack Transformer baseline": "Crack Trans.",
        "ViT crack detector baseline": "ViT crack",
        "CrackYOLO-R full": "CrackYOLO-R",
        "CrackYOLO-R-seg full": "CrackYOLO-R-seg",
        "CrackYOLO-R-nano": "CrackYOLO-R-nano",
    }

    for ax, (title, ylabel, data, direction) in zip(flat_axes, panels):
        if not data:
            ax.axis("off")
            continue
        labels = [label_map.get(method, method) for method, _, _ in data]
        vals = [value for _, value, _ in data]
        xs = list(range(len(data)))
        ax.bar(
            xs,
            vals,
            color=[colors.get(method, "#666666") for method, _, _ in data],
            alpha=0.92,
            edgecolor="black",
            linewidth=0.4,
        )
        ax.set_title(title, fontsize=9, fontweight="bold")
        ax.set_ylabel(ylabel)
        ax.set_xticks(xs)
        ax.set_xticklabels(labels, rotation=35, ha="right")
        ax.grid(axis="y", alpha=0.2, linewidth=0.6)
        spread = max(vals) - min(vals)
        pad = max(0.04, spread * 0.18)
        lo = min(vals) - pad
        hi = max(vals) + pad
        if ylabel == "FP/image":
            lo = max(0.0, lo)
        elif "FPS" not in ylabel:
            lo = max(0.0, lo)
            hi = min(1.0, hi)
        ax.set_ylim(lo, hi)
        ax.text(
            0.98,
            0.92,
            "lower is better" if direction == "lower" else "higher is better",
            transform=ax.transAxes,
            ha="right",
            va="top",
            fontsize=7,
            color="#555555",
        )

    flat_axes[-1].axis("off")
    flat_axes[-1].text(
        0.02,
        0.8,
        "Panels use metric-specific axes.\n"
        "Bars are planning centers only;\n"
        "planning ranges remain in CSV.",
        fontsize=9,
        va="top",
    )
    fig.suptitle("CrackYOLO-R Planning Forecast Centers by Metric Family", fontsize=12, fontweight="bold")
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)
    draw_module_detail_figure(plt, root / "figures" / "crackyolo_module_detail.png")
    draw_mechanism_equation_figure(plt, root / "figures" / "crackyolo_mechanism_equations.png")
    draw_architecture_figure(plt, root / "figures" / "crackyolo_architecture.png")
    draw_benchmark_matrix_figure(plt, root / "figures" / "planned_benchmark_matrix.png")
    print(f"Wrote {output} ({output.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
